/**
 * HRPC Type Definitions
 *
 * All HRPC (Hypercore RPC) and worklet RPC type definitions.
 * These types define the communication protocol between the React Native
 * app and the worklet runtime.
 */

import { HRPC as PearHRPC } from '@tetherto/pear-wrk-wdk'

// Re-export types from pear-wrk-wdk
export {
  LogType,
  type LogRequest,
  type WorkletStartRequest,
  type WorkletStartResponse,
  type DisposeRequest,
  type CallMethodRequest,
  type CallMethodResponse,
} from '@tetherto/pear-wrk-wdk'

// Re-export HRPC class/interface
export type HRPC = PearHRPC

// ============================================================================
// Bundle Configuration
// ============================================================================

/**
 * HRPC Constructor Interface
 *
 * Interface for the HRPC class constructor.
 */
export interface HRPCConstructor {
  new (stream: unknown): HRPC
}

/**
 * Bundle Configuration
 *
 * Configuration for the worklet bundle and HRPC class.
 * Generated by wdk-worklet-bundler CLI tool.
 *
 * @example
 * ```typescript
 * import { bundle, HRPC } from './.wdk'
 *
 * <WdkAppProvider
 *   bundle={{ bundle, HRPC }}
 *   networkConfigs={...}
 * >
 *   <App />
 * </WdkAppProvider>
 * ```
 */
export interface BundleConfig {
  /** The worklet bundle (compiled JavaScript for the worklet runtime) */
  bundle: unknown
  /** The HRPC class constructor for RPC communication with the worklet */
  HRPC: HRPCConstructor
}

// ============================================================================
// Legacy Helpers (Deprecated/No-op)
// ============================================================================

/**
 * Extended HRPC interface
 * The base HRPC class now includes all methods. Use HRPC directly.
 */
export type ExtendedHRPC = HRPC

/**
 * Type guard to check if HRPC instance has extended methods
 * @deprecated The base HRPC class now includes all methods. Always returns true.
 */
export function isExtendedHRPC(hrpc: HRPC): hrpc is ExtendedHRPC {
  return true
}

/**
 * Safely cast HRPC to ExtendedHRPC
 * @deprecated The base HRPC class now includes all methods. Returns input as-is.
 */
export function asExtendedHRPC(hrpc: HRPC): ExtendedHRPC {
  return hrpc
}
